export const ROUTES = {
  public: {
    home: "/",
    about: "/about",
    features: "/features",
    contact: "/contact",
    privacy: "/privacy-policy",
    terms: "/terms",
  },

  auth: {
    login: "/login",
    register: "/register",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    unauthorized: "/unauthorized",
  },

  candidate: {
    dashboard: "/candidate/dashboard",
    profile: "/candidate/profile",
    resumeUpload: "/candidate/resume-upload",
    resumeReview: "/candidate/resume-review",
    jobs: "/candidate/jobs",
    recommendedJobs: "/candidate/recommended-jobs",
    savedJobs: "/candidate/saved-jobs",
    applications: "/candidate/applications",
    skillGap: "/candidate/skill-gap",
    feedback: "/candidate/feedback",
    interviews: "/candidate/interviews",
    notifications: "/candidate/notifications",
    chatbot: "/candidate/chatbot",
    settings: "/candidate/settings",
  },

  employer: {
    dashboard: "/employer/dashboard",
    profile: "/employer/profile",
    postJob: "/employer/post-job",
    aiJobDescription: "/employer/ai-job-description",
    jobs: "/employer/jobs",
    applications: "/employer/applications",
    candidateRanking: "/employer/candidate-ranking",
    candidateComparison: "/employer/candidate-comparison",
    interviews: "/employer/interviews",
    feedback: "/employer/feedback",
    reports: "/employer/reports",
    notifications: "/employer/notifications",
    settings: "/employer/settings",
  },

  admin: {
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    candidates: "/admin/candidates",
    employers: "/admin/employers",
    jobs: "/admin/jobs",
    skills: "/admin/skills",
    aiModels: "/admin/ai-models",
    modelEvaluation: "/admin/model-evaluation",
    resumeExtractionReview: "/admin/resume-extraction-review",
    chatbotKnowledge: "/admin/chatbot-knowledge",
    emailTemplates: "/admin/email-templates",
    notifications: "/admin/notifications",
    reports: "/admin/reports",
    auditLogs: "/admin/audit-logs",
    settings: "/admin/settings",
  },
};